config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'

  devise_for :users, path_names: { sign_in: 'login' , sign_out: 'logout', sign_up: 'register' }

  resources :portifolios

  resources :blogs do
    member do
        get :toggle_status
    end
  end

  root to: 'pages#home'

end

app/models/portifolio.rb
class Portifolio < ApplicationRecord
  has_many :technologies

  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body, :main_image, :thumg_image

  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }
end

app/controllers/portifolios_controller.rb
class PortifoliosController < ApplicationController
  layout "portifolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfolio_items = Portifolio.all
  end

  def new
    @portfolio_item = Portifolio.new
  end

  def create
    @portfolio_item = Portifolio.new(portifolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portifolios_path, notice: 'Your Portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portifolio.find(params[:id])
  end

  def update
    @portfolio_item = Portifolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portifolio_params)
        format.html { redirect_to portifolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portifolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portifolio.find(params[:id])

    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portifolios_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  private

  def portifolio_params
    params.require(:@portfolio).permit(:title, :subtitle, :body)
  end

end

app/helpers/portifolios_helper.rb
module PortifoliosHelper
end

app/views/portifolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
    </div>

    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<%end %>

app/views/portifolios/_portfolio_item.html.erb
<p><%= link_to item.title, portifolio_path(item.id) %></p>

<p><%= item.subtitle %></p>

<p><%= item.body %></p>

<p><%= item.main_image %></p>

<%= image_tag item.thumg_image if !item.thumg_image .nil? %>
<%= link_to "Edit", edit_portifolio_path(item.id) if logged_in?(:site_admin) %>
<a href="/portifolios/<%= item.id %>/edit">Edit Two</a> #outra forma de fazer o edit
<%= link_to 'Destroy', portifolio_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>

app/views/portifolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<% @portfolio_items_angular.each do |item| %>
  <p><%= link_to item.title, portifolio_path(item.id) %></p>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <p><%= item.main_image %></p>
  <%= image_tag item.thumg_image if !item.thumg_image .nil? %>
  <%= link_to "Edit", edit_portifolio_path(item.id) %>
  <a href="/portifolios/<%= item.id %>/edit">Edit Two</a> #outra forma de fazer o edit
  <%= link_to 'Destroy', portifolio_path(item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portifolios/edit.html.erb
<h1>Edit this Portfolio</h1>

<%= render "form", portifolio_item: @portifolio_item %>

app/views/portifolios/index.html.erb
<h1>Portfolio Items</h1>

<a href="portifolios/new" >Create New Item</a>

<%= link_to "Create New Item", new_portifolio_url if logged_in?(:site_admin) %> #outra maneira de fazer

<p>
  <%= new_portifolio_path %>
</p>

<p>
  <%= new_portifolio_url %>
</p>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portifolios/new.html.erb
<h1>Create a new Portfolio</h1>

<%= render "form", portifolio_item: @portifolio_item %>

app/views/portifolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>